version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    env_file: .env
    environment:
      POSTGRES_HOST: db
      RAILS_ENV: development
      RACK_ENV: develobpment
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file: .env
volumes:
  db-volume:
    driver: local
